name: Barfbook
description: Das Barfbuch für unterwegs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  file_picker: ^5.2.7
  path_provider: ^2.0.14
  get: ^4.6.5
  animations: ^2.0.7
  supabase_flutter: ^1.4.1
  flutter_typeahead: ^4.3.7
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.61.0
  keyboard_actions: ^4.2.0
  table_calendar: ^3.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/
    - assets/icons/
    - assets/icons/recipe/
    - assets/fonts/lexend/
    