name: Barfbook
description: Das Barfbuch für unterwegs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  json_theme: ^4.0.0
  settings_ui: ^2.0.2
  get: ^4.6.5
  animations: ^2.0.7
  supabase_flutter: ^1.4.1
  image_picker: ^0.8.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lexicon/whatis/
    - assets/images/
    - assets/themes/
    
google_sign_in_web: ^0.9.1