// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZFOVahFsMdMxQkL3dEivB2iHQw_fUK-4',
    appId: '1:946526640203:web:b32a7338b27356028f95ce',
    messagingSenderId: '946526640203',
    projectId: 'barfbook-70fc0',
    authDomain: 'barfbook-70fc0.firebaseapp.com',
    storageBucket: 'barfbook-70fc0.appspot.com',
    measurementId: 'G-PPZLQYCQH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZByw8ysVQHgqWHogxbBH81OCHLiz6vU',
    appId: '1:946526640203:android:bc5ce2e6e35700828f95ce',
    messagingSenderId: '946526640203',
    projectId: 'barfbook-70fc0',
    storageBucket: 'barfbook-70fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8txpV7WStbbjja_3kdIr5IAWICfgUtik',
    appId: '1:946526640203:ios:931792b7a8fa92d48f95ce',
    messagingSenderId: '946526640203',
    projectId: 'barfbook-70fc0',
    storageBucket: 'barfbook-70fc0.appspot.com',
    iosClientId: '946526640203-k2ms7id1uuhgj67h4kkkocf4a8658k3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.barfbookapp',
  );
}
